/**
 *
 * Copyright 2009-2011 Streamsource AB
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package se.streamsource.streamflow.client.ui.administration;

/**
 * i18n resources for the "Administration" view
 */
public enum AdministrationResources
{
   window_name,
   projects_tab,
   groups_tab,
   forms_tab,
   selected_forms_tab,
   name_label,
   old_password,
   new_password,
   confirm_password,
   passwords_do_not_match,
   old_password_incorrect,
   could_not_refresh,
   could_not_remove_organisation_with_open_projects,
   move_to,
   administrators_tab,
   merge_to,
   username_label,
   password_label,
   confirm_password_label,
   passwords_dont_match,
   user_enabled_label,
   import_users,
   users_tab,
   join_organization,
   import_files,
   create_account_name,
   create_account_server,
   create_account_username,
   create_account_password,
   mandatory,
   description_label,
   could_not_get_field,
   date_field_type,
   type_label,
   add_project_title,
   change_project_title,
   add_label_title,
   rename_label_title,
   choose_label_title,
   choose_form_title,
   add_group_title,
   rename_group_title,
   add_user_or_group_title,
   add_role_title,
   create_ou_title,
   change_ou_title,
   create_new_form,
   labels_tab,
   selected_labels_tab,
   create_user_title,
   reset_password_title,
   add_casetype_title,
   rename_casetype_title,
   choose_casetypes_title,
   casetypes_tab,
   page_break_field_type,
   comment_field_type,
   comment_label,
   number_field_type,
   width_label,
   rows_label,
   integer_label,
   checkboxes,
   combobox,
   listbox,
   optionbuttons,
   openselection,
   textarea,
   text,
   number,
   date,
   comment,
   page_break,
   field_type_selection,
   add_field_to_form,
   add_page_title,
   invalid_value,
   rename,
   selected_casetypes_tab,
   choose_move_to,
   search_users_or_groups,
   add_resolution_title,
   resolutions_tab,
   choose_resolution_title,
   selected_resolutions_tab,
   resolve,
   accesspoints_tab,
   proxyusers_tab,
   add_accesspoint_title,
   change_accesspoint_title,
   could_not_create_accesspoint_name_already_exists,
   could_not_create_accesspoint,
   could_not_rename_accesspoint_name_already_exists,
   members_tab,
   remove_proxyuser_title,
   form_id_label,
   hint_label,
   regularexpression_label,
   field_id_label,
   templates_tab,
   cols_label,
   forminfo_tab,
   formpages_tab,
   attachment,
   add_signature_title,
   group_title,
   user_title,
   choose_default_access_type,
   caseaccessdefaults_tab,
   choose_move_casetype_to,
   choose_accesspoint_title,
   emailaccesspoints_tab,
   accesspoint,
   email,
   subject, emailTemplates,
   add_email_accesspoint,
   formsignatures_tab,

   choose_recipient_title,
   filters_tab,
   add_filter_title,
   enabled,
   all,
   any,
   filter_rules,
   filter_actions,
   send_email_to,
   match_label,
}